#!usr/bin/env zsh

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=150
SAVEHIST=150
setopt autocd beep notify
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/r/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# PROMPT='$B%F{green}%1~ '
PROMPT='%B%F{green}%1~%f%b %F{yellow}%#%f '


. ~/.config/zsh/alias.sh
. ~/.config/zsh/export.sh
. ~/.config/zsh/function.sh
. ~/.config/zsh/zsh-syntax-highlight
. ~/.config/zsh/tmux-ssh.sh

eval "$(zoxide init zsh)"

# If not running interactively, don't do anything
[[ $- != *i* ]] && return


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/r/project/aem-gcloud-test-project/google-cloud-sdk/path.zsh.inc' ]; then . '/home/r/project/aem-gcloud-test-project/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/r/project/aem-gcloud-test-project/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/r/project/aem-gcloud-test-project/google-cloud-sdk/completion.zsh.inc'; fi

# bun completions
[ -s "/home/r/.bun/_bun" ] && source "/home/r/.bun/_bun"

# pnpm
export PNPM_HOME="/home/r/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
