#!usr/bin/env zsh

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=150
SAVEHIST=150
setopt autocd beep notify
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/r/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# PROMPT='$B%F{green}%1~ '
PROMPT='%B%F{green}%1~%f%b %F{yellow}%#%f '


. ~/.config/zsh/alias.zsh
. ~/.config/zsh/export.zsh
. ~/.config/zsh/function.zsh
. ~/.config/zsh/zsh-syntax-highlight

eval "$(zoxide init zsh)"

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'

