#!/usr/bin/env zsh
# Sadece en gerekli renklendirmeleri yükle
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)

# arch icin
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# # ubuntu icin
# source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

ZSH_HIGHLIGHT_STYLES[default]='fg=white'
ZSH_HIGHLIGHT_STYLES[command]='fg=green,bold'
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=red,bold'
ZSH_HIGHLIGHT_STYLES[path]='fg=cyan'
ZSH_HIGHLIGHT_STYLES[option]='fg=yellow'
ZSH_HIGHLIGHT_STYLES[quoted]='fg=magenta'
ZSH_HIGHLIGHT_STYLES[assign]='fg=blue'
