#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

export EDITOR=nvim
# export HOTKEYS_PATH=~/.config/superfile/vimHotkeys.toml

. ~/.bash_alias
. ~/.bash_function
